services:
  web-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://admin:admin@mongo:27017
    depends_on:
      - mongo
      - alloy

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
  
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./config/alloy-config.yaml:/etc/alloy/config.alloy
    command: ["run --server.http.listen-addr=0.0.0.0:12345","/etc/alloy/config.alloy"]
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
    environment:
      - TEMPO_STORAGE=MEMORY
      - TEMPO_RECEIVER=GRPC
      - TEMPO_RECEIVER_GRPC_PORT=3200
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo/config.yaml
    command: ["-config.file=/etc/tempo/config.yaml"]
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - tempo
    
volumes:
  mongo-data:
    driver: local
  grafana-storage:
    driver: local