services:
  web-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OTEL_TRACES_EXPORTER="otlp"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://tempo:4317"
      - OTEL_NODE_RESOURCE_DETECTORS="env,host,os"
      - OTEL_SERVICE_NAME="web-app"
      - NODE_OPTIONS="--require @opentelemetry/auto-instrumentations-node/register"
      - MONGO_URL=mongodb://admin:admin@mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
  
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4318:4318"
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo/config.yaml
    command: ["-config.file=/etc/tempo/config.yaml"]
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - tempo
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./config/prometheus-config.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    
volumes:
  mongo-data:
    driver: local
  grafana-storage:
    driver: local