services:
  web-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://admin:admin@mongo:27017
      - TEMPO_URL=http://tempo:4318
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
  
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4318:4318"
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo/config.yaml
    command: ["-config.file=/etc/tempo/config.yaml"]
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - tempo
    
volumes:
  mongo-data:
    driver: local
  grafana-storage:
    driver: local